indica/datatypes.py, indica/readers/adas.py, snippets/fac_profiles.py, snippets/test_adas_fractabu.py, tests/unit/data_strategies.py, tests/unit/readers/test_adas_reader.py
I thought a pull request would be more appropriate for this than an issue. From @marcosertoli on #24:
> Please check implementation of get_adf15 in ADAS class. Also added ADF15 general datatypes, but meaningful dictionary still needs to be implemented.
I have marked the PR as a Work in Progress (WIP), to indicate that it's not yet ready to be merged.
=> WIP: Added to adas class new adf15 reading capability

indica/readers/adas.py, setup.cfg
This code has too high a cyclomatic complexity and is causing linting
to fail. The issue will be addressed in #29 but until then this code
is being removed from master. Its presence is preventing other PRs
from being merged and causing people to turn off the pre-commit
linting (introducing yet more problems).
=> Remove ADF15 reader code

.pre-commit-config.yaml, indica/data.py, indica/equilibrium.py, indica/readers/surf_los.py, tests/unit/data_strategies.py, tests/unit/readers/test_surf.py, tests/unit/test_equilibrium.py, tests/unit/test_equilibrium_single.py
Currently the `enclosed_volume(...)` is implemented as well as a rudimentary unit test for it. Additionally `Btot(...)` is also partially implemented but work on the toroidal magnetic field and the coordinate systems inside the function remains.
=> Issue #10 : Gadgil48/10 equilibrium methods

.gitignore, indica/equilibrium.py, indica/numpy_typing.py, tests/unit/test_equilibrium_single.py
=> Separated calculation of cross-sectional area and now using trapezoidal rule for integration

.gitignore, indica/equilibrium.py, indica/numpy_typing.py, tests/unit/test_equilibrium_single.py
Reverts ukaea/Indica#43 as per @marcosertoli request
=> Revert "Separated calculation of cross-sectional area and now using trapezoidal rule for integration"

indica/operators/main_ion_density.py, tests/unit/operators/test_impurity_concentration.py, tests/unit/operators/test_main_ion_density.py
Recommended merge order is to merge in the order the issues are listed in "Complete core computational modules" milestone.
Closes #21
=> Main ion density calculation

indica/equilibrium.py, indica/operators/spline_fit.py, indica/utilities.py, tests/unit/operators/test_spline_fit.py, tests/unit/test_equilibrium_single.py
=> Fix for issue #36

indica/operators/atomic_data.py, tests/unit/operators/test_atomic_data.py
=> Changes to PowerLoss() in atomic_data.py

indica/operators/atomic_data.py, indica/operators/centrifugal_asymmetry.py, indica/operators/impurity_concentration.py, indica/operators/main_ion_density.py, indica/operators/mean_charge.py, indica/utilities.py, tests/unit/operators/test_atomic_data.py, tests/unit/test_utilities.py
=> Fix for issue #55

indica/numpy_typing.py, indica/operators/atomic_data.py, indica/utilities.py, tests/unit/operators/test_atomic_data.py, tests/unit/operators/test_centrifugal_asymmetry.py, tests/unit/operators/test_impurity_concentration.py, tests/unit/operators/test_main_ion_density.py, tests/unit/operators/test_mean_charge.py
=> Restructure of atomic_data.py

indica/utilities.py, tests/unit/test_utilities.py
=> Fixes dropped channel handling in utilities.input_check()

indica/readers/adas.py
=> Fixes mixing up of rows and columns for ADF15 data import

indica/converters/impact_parameter.py, indica/converters/lines_of_sight.py, indica/readers/abstractreader.py, tests/unit/converters/test_lines_of_sight.py, tests/unit/operators/test_impurity_concentration.py, tests/unit/readers/mock_reader.py
=> Change labelling of start and end points for LoS transforms.

indica/operators/invert_radiation.py, poetry.lock, pyproject.toml
=> Upgraded pre-commit to 2.17.0

indica/operators/centrifugal_asymmetry.py, indica/operators/impurity_concentration.py, indica/operators/main_ion_density.py, tests/unit/operators/test_centrifugal_asymmetry.py, tests/unit/operators/test_impurity_concentration.py, tests/unit/operators/test_main_ion_density.py
=> Changed instances of dimension label "elements" to "element".

.github/workflows/docs.yml, .github/workflows/quality.yml, .github/workflows/tests.yml
=> Try to fix CI hanging.

indica/converters/line_of_sight.py, tests/unit/converters/test_line_of_sight.py
Closes #82 
Minor changes to convert methods and x1, x2 labels. 
Commits passed local pre-commit checks.
=> Jmwood94 0/82 line of sight transform

indica/readers/abstractreader.py, indica/readers/available_quantities.py, indica/readers/ppfreader.py, tests/unit/readers/fake_salclient.py, tests/unit/readers/ppf_samples.json, tests/unit/readers/test_ppf_reader.py
Fixes #136 
- Use JSON
- Make `available_quantities` a `classmethod`
- Sample quantities for testing PPFReader from `available_quantities`
- Improve `FakeSALClient`
=> PPFReader test fixes and improvements

.github/workflows/docs.yml, doc/conf.py
=> Remove link checking from doc tests

indica/operators/impurity_concentration.py
=> Update error message for new compatible coordinates.

.github/workflows/docs.yml
=> Fix docs not building in CI

indica/readers/abstractreader.py
=> Add a warning when some quantities less than 0

.github/workflows/quality.yml, .github/workflows/tests.yml
Fixes #179 
Tested with poetry 1.2.0 but could not install indica.
=> Use poetry 1.1.15 in CI - fix broken install

indica/operators/extrapolate_impurity_density.py
=> Add input checks to optimize_perturbation

.gitignore, indica/operators/atomic_data.py, indica/operators/bolometry_derivation.py, indica/operators/centrifugal_asymmetry.py, indica/operators/extrapolate_impurity_density.py, indica/operators/impurity_concentration.py, indica/operators/main_ion_density.py, indica/operators/mean_charge.py, indica/utilities.py, tests/unit/operators/test_centrifugal_asymmetry.py, tests/unit/test_utilities.py
Fixes #150 
Needs more work to verify asymmetry_from_rho_theta.
Currently returning centre full on NaNs.
=> Accept rho, theta in extrapolate_impurity_density.

indica/readers/available_quantities.py, indica/readers/ppfreader.py, tests/unit/readers/ppf_samples.json, tests/unit/readers/test_ppf_reader.py
Adds additional CXRS DDAs and concentration reading capabilities
=> Expand CXRS reading

indica/readers/surf_los.py, tests/unit/readers/test_surf.py
Fixes #175 
Change calculation of LOS angle to match SURF calculation
Simplify calculation steps from original
=> Update SXR LOS calculation

.github/workflows/docs.yml, .github/workflows/quality.yml, .github/workflows/tests.yml
=> Allow manually triggered CI runs

.pre-commit-config.yaml, indica/session.py, poetry.lock, pyproject.toml, setup.cfg
Fixes #126 
Bump scipy and mypy versions that were causing problems, move and fix mypy config.
=> Update minimum versions of scipy and mypy

indica/profiles_gauss.py, indica/readers/abstractreader.py, indica/workflows/load_modelling_plasma.py, indica/workflows/profile_workflows.py, tests/unit/readers/test_adas_reader.py
To be merged into st40, then used as basis to further develop the profile workflows to include PCA dimensionality reduction.
=> Adapting profile workflows for PCA

.github/workflows/quality.yml, .github/workflows/tests.yml
Changed python version also in githib CI  workflows
=> Merged in master pyproject.toml and adapted for ST40 use.

poetry.lock, pyproject.toml
New Python 3.9 environment makes sklearn installation possible.
GPR fit now works in Indica environment
=> Added sklearn to environment

indica/equilibrium.py
Adding capability of recomputing rho-poloidal if fbnd or faxs are corrupted.
=> Equilibrium fix

indica/operators/invert_radiation.py, snippets/test_bolometry_inversion.py, snippets/test_sxr_inversion.py, tests/unit/operators/test_invert_radiation.py
=> Return EmissivityProfile from InvertRadiation

indica/equilibrium.py
Simple fix to move the equilibrium psi and other quantities based on a user supplied R_shift / z_shift
=> Equilibrium shifting R / z in initialisation

indica/operators/tomo_1D.py
=> Corrected bug that wasn't accounting for self.valid in Tomo1D

indica/examples/example_diagnostic_models.py, indica/models/__init__.py, indica/models/abstract_diagnostic.py, indica/models/bolometer_camera.py, indica/models/charge_exchange_spectrometer.py, indica/models/diode_filters.py, indica/models/equilibrium_reconstruction.py, indica/models/helike_spectrometer.py, indica/models/interferometer.py, indica/models/sxr_camera.py, indica/models/thomson_scattering.py, indica/readers/mdsutils.py, indica/readers/modelreader.py, indica/workflows/model_coordinator.py, tests/integration/models/test_diagnostic_models.py, tests/integration/models/test_helike_spectroscopy.py, tests/integration/workflows/test_bayes_workflow.py, tests/integration/workflows/test_bda_run.py, tests/integration/workflows/test_model_coordinator.py
- Some tidying up of the file names
- Model Coordinator has been added (Can decide to merge this functionality or not with modelreader)
=> refactored model names to be consistent and self.transform as generic attribute

indica/models/pinhole_camera.py
Custom PowerLoss operator is used if the PinholeCamera has it. Otherwise use the plasma Lz.
=> pinhole camera can be initialised with powerloss operator

indica/examples/example_diagnostic_models.py, indica/models/passive_spectrometer.py, tests/integration/models/test_diagnostic_models.py
PassiveSpectrometer takes PECs generated from ADF15s and calculates line intensities and an observed spectra given LOS and plasma parameters.
Not optimised that well yet... Model call can take up to 10s for 1 element.
=> Passive Spectrometer Model

indica/models/helike_spectrometer.py
I added the theoretical estimate for the crystal calibration and the conversion from counts/s/nm to counts/s/pixel.
=> Crystal Calibration now correctly accounts for pixel binning.
